### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by houshuaipeng** [FoundationVision/GLEE#3]
作者您好，非常感谢您的工作，我在本地运行时，报了缺少文件的错误：
Config '/mnt/yrfs/userdata/hsp/projects/GLEE/app/GLEE/configs/R50.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "app.py", line 90, in <module>
    GLEEmodel_r50 = GLEE_Model(cfg_r50, None, device, None, True).to(device)
  File "/mnt/yrfs/userdata/hsp/projects/GLEE/app/GLEE/glee/models/glee_model.py", line 67, in __init__
    self.text_encoder = CLIPTextModel.from_pretrained('GLEE/clip_vit_base_patch32')
  File "/home/hsp/anaconda3/envs/GLEE/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3206, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory GLEE/clip_vit_base_patch32.
请问我需要在哪里下载对应的文件呢？

**Comment by houshuaipeng** [comment]
已经在huggingface的文件夹（https://huggingface.co/spaces/Junfeng5/GLEE_demo/tree/main/GLEE/clip_vit_base_patch32）中找到了，已解决
