### ISSUE TITLE
export2onnx

### ISSUE THREAD

**Issue by YSYS101010000** [FoundationVision/GLEE#53]
我想将pth 模型导出onnx ,模型为“GLEE_SwinL_Scaleup10m.pth” 。
环境：
torch 2.1.0+cu121 
torchvison 0.16.0+cu121 
修改：
对 ./projects/GLEE/glee/models/glee_model.py/glee_model.py 中的forward 进行修改，
问题：
转换onnx过程中出现以下错误：
Traceback (most recent call last):
  File "/mnt/data/ysbo/python_examples/GLEE-main_infertest/export2onnx.py", line 109, in <module>
    torch.onnx.export(model_, dummy_input, ONNX_name, verbose=True, input_names=input_names,do_constant_folding=True,
  File "/home/xuekai/xuekai/software/miniconda3/envs/GLEEBAK/lib/python3.9/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/xuekai/xuekai/software/miniconda3/envs/GLEEBAK/lib/python3.9/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/xuekai/xuekai/software/miniconda3/envs/GLEEBAK/lib/python3.9/site-packages/torch/onnx/utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "/home/xuekai/xuekai/software/miniconda3/envs/GLEEBAK/lib/python3.9/site-packages/torch/onnx/utils.py", line 595, in _optimize_graph
    _C._jit_pass_onnx_autograd_function_process(graph)
RuntimeError: required keyword attribute 'Subgraph' is undefined

特此请教一下，问题如何解决

**Comment by HYJJJJJJJJ** [comment]
是不是把torch.nn.Module转cpu再转onnx了？可以尝试下直接把gpu模型转onnx，应该就不会报这个问题
